[package]
name = "examplelang"
code = "ex"
author = "darcy"
translations = [["eo", "esperanto"], ["en", "english"]]

[options]
# minify = false

[files]
style = "style.scss"
# build = "./build/"
# source = "./assets/"
# main = "index.ling"
# phoner = "phoner"
# dict = "dict.dlst"
# template = "template.html"
