[package]
name = "ivalingo"
code = "iv"
author = "darcy"
translations = [["eo", "esperanto"], ["en", "english"]]

[options]
minify = false

# [files]
# build = "./build/"
# source = "./assets/"
# main = "main.ling"
# phoner = "phoner"
# dict = "dict.dlst"
# template = "template.html"
